[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "generp_theme"
version = "0.0.1"
description = "Custom Desk theme"
authors = [{ name = "You", email = "you@example.com" }]
license = { text = "MIT" }
readme = "README.md"
