[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "generp_theme"
version = "0.0.1"
description = "generp_theme"
authors = [{ name = "Ahmed", email = "ahmed@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
